name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg

    - name: Build application
      run: go build -o /app/bin/organize

    - name: Run application
      run: |
        mkdir -p /app/bin
        cp organize /app/bin/
        /app/bin/organize /organize
