name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg

    - name: Build application
      run: go build -o bin/organize

    - name: Download and set up ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        mv ngrok /usr/local/bin
        ngrok authtoken ${{ secrets.NGROK_TOKEN }}

    - name: Start ngrok tunnel
      run: ngrok tcp 23234 &

    - name: Run application
      run: |
        bin/organize /organize

    - name: Display ngrok URL
      run: curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'
