name: Docker Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t my-organize-app .

      - name: Run Docker container
        run: docker run -d -p 23234:23234 --name organize-app my-organize-app

      - name: Wait for Docker container to start
        run: sleep 10

      - name: Test HTTP response code
        run: |
          status_code=$(docker exec organize-app curl -o /dev/null -s -w "%{http_code}" http://localhost:23234/organize)
          echo "HTTP Status Code: $status_code"
          if [ "$status_code" -eq 200 ]; then
            echo "Test passed! HTTP 200 OK received."
          else
            echo "Test failed! HTTP status code was not 200."
            exit 1
          fi

      - name: Clean up
        run: docker stop organize-app && docker rm organize-app
